baseURL = "https://mikewebbtech.github.io/mikewebb-tech/"
languageCode = "en-us"
title = "Mike Webb Tech"
summaryLength = 30
enableEmoji = true

[module]
[[module.imports]]
path = "github.com/KKKZOZ/hugo-admonitions"

[menus]
[[menus.main]]
name = "Home"
pre = "fa-house"
url = "/"
weight = 10
[[menus.main]]
name = "Articles"
pre = "fa-file-code"
url = "/articles/"
weight = 20
[[menus.main]]
name = "Categories"
pre = "fa-list"
url = "/categories/"
weight = 30
[[menus.main]]
name = "Series"
pre = "fa-layer-group"
url = "/series/"
weight = 40
[[menus.main]]
name = "Tags"
pre = "fa-tags"
url = "/tags/"
weight = 50
[[menus.main]]
name = "About"
pre = "fa-circle-info"
url = "/about/"
weight = 15

[taxonomies]
tag = "tags"
category = "categories"
series = "series"

[params]
favicon = "/img/favicon.ico"
dateFormat = "Jan 2, 2006"
github = "https://github.com/mikewebbtech"
linkedin = "https://www.linkedin.com/in/michael-webb-1a36b8a5/"

[pagination]
disableAliases = false
pagerSize = 500

[markup]


[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true
[markup.goldmark.parser]
[markup.goldmark.parser.attribute]
block = true
